# 决哥例外

> 原文:[https://www.javatpoint.com/django-exceptions](https://www.javatpoint.com/django-exceptions)

异常是导致程序失败的异常事件。为了处理这种情况，Django 使用自己的异常类，并且也支持所有核心 Python 异常。

Django 核心异常类在 **django.core.exceptions** 模块中定义。该模块包含以下类。

## 决哥例外班

| 例外 | 描述 |
| appregisterynotready | 在应用程序加载过程之前尝试使用模型时会引发此问题。 |
| 对象不存在 | 的基类不存在异常。 |
| EmptyResultSet | 如果查询没有返回任何结果，则会引发此异常。 |
| 字段不存在 | 当请求的字段不存在时，它会引发。 |
| 多个对象已返回 | 如果只需要一个对象，但返回多个对象，则查询会引发此异常。 |
| 可疑操作 | 当用户执行了从安全角度来看应被视为可疑的操作时，会引发此异常。 |
| 权限被拒绝 | 当用户无权执行请求的操作时，会引发此问题。 |
| 视图不存在 | 当请求的视图不存在时，由 django.urls 引发。 |
| 中间仓库未使用 | 当服务器配置中不使用中间件时，会引发此问题。 |
| 改进配置 | 当 Django 以某种方式配置不正确时，就会引发 ImproperlyConfigured 异常。 |
| 字段错误 | 当模型字段出现问题时，会引发此问题。 |
| 验证错误 | 当数据验证未通过表单或模型字段验证时，会引发此问题。 |

## 决哥 URL 解析异常

这些异常在 **django.urls** 模块中定义。

| 例外 | 描述 |
| 解析器 404 | 当传递给 resolve()函数的路径没有映射到视图时，会引发此异常。 |
| NoReverseMatch | 当根据提供的参数无法识别您的 URLconf 中的匹配 URL 时，会引发此问题。 |

## Django 数据库异常

以下异常在 **django.db** 模块中定义。

| 例外 | 描述 |
| 数据库错误 | 当数据库不可用时会发生这种情况。 |
| 完整性错误 | 它在执行插入查询时发生。 |
| 数据错误 | 当数据库中出现与数据相关的问题时，它会引发。 |

## 决哥 Http 异常

以下异常在 **django.http** 模块中定义。

| 例外 | 描述 |
| 不可恢复后错误 | 当用户取消上载时引发。 |

## Django 交易例外

事务异常在 django.db.transaction 中定义。

| 例外 | 描述 |
| 事务管理器错误 | 对于与数据库事务相关的任何和所有问题，都会引发此问题。 |

## 姜戈异常示例

假设，我们想要获取 id = 12 的员工记录，我们的视图函数将如下所示。如果找不到数据，它会引发一个不存在的异常。这是 Django 的内置例外。

**//view . py**

```

def getdata(request):
    data = Employee.objects.get(id=12)
    return HttpResponse(data)

```

・T0️ // urls.py ・T1️

```

path('get',views.getdata)

```

它显示了以下异常，因为在 id 12 处没有可用的记录。

**输出:**

![Django Exception example](../Images/083330c37a7997e852f6eaa96b5a67b2.png)

我们可以通过使用 try 和 except 来处理它，现在让我们来处理这个异常。

**//view . py**

```

def getdata(request):
    try:
        data = Employee.objects.get(id=12)
    except ObjectDoesNotExist:
        return HttpResponse("Exception: Data not found")
    return HttpResponse(data);

```

**输出:**

![Django Exception output](../Images/b33eaab8f377ea8c48e9987f508e6878.png)